apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: exips-role
rules:
  - apiGroups: [""]  # "" indicates the core API group
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]  # "" indicates the core API group
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
