apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: exips
  namespace: exips
resources:
  - clusterrolebinding.yaml
  - clusterrole.yaml
  - namespace.yaml
  - pod.yaml
  - serviceaccount.yaml
