apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: exips

resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml

# generatorOptions:
#   disableNameSuffixHash: true

configMapGenerator:
  - name: exips-config
    literals:
      - DEBUG="false"
      - INTERVAL=15s
      - RESYNC=1m
      - SERVICE_NAME=exips
      - SERVICE_NAMESPACE=exips
